<footer class="py-3 my-4">
  <ul class="nav justify-content-center border-bottom pb-3 mb-3">
    <li class="nav-item">
      <a href="index.php" class="nav-link px-2 text-muted">About Us</a>
    </li>
    <li class="nav-item">
      <a href="index.php" class="nav-link px-2 text-muted">Help</a>
    </li>
    <li class="nav-item">
      <a href="index.php" class="nav-link px-2 text-muted">Contact Us</a>
    </li>
  </ul>
  <p class="text-center text-muted">Developed by SEPA Group 19</p>
  <p class="text-center text-muted">CityLogistics ©2023</p>
</footer>
