<header>
  <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-primary">
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarTogglerDemo01"
      aria-controls="navbarTogglerDemo01"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand mb-0 h1" href="index.php"
        ><img
          src="styles/images/logo.svg"
          width="30"
          height="30"
          class="d-inline-block align-top"
          alt=""
        />
        &nbsp CityLogistics</a
      >
    </div>
  </nav>
</header>
