<div class="sidebar bg-primary">
  <div class="logo-details">
    <i class="bx bx-sitemap"></i>
    <span class="logo_name">CityLogistics</span>
  </div>
  <ul class="nav-links">
    <li>
      <a href="addDATASET.php" class="menu-item">
        <i class="bx bx-data"></i>
        <span class="links_name">Set up routes</span>
      </a>
    </li>
    <li>
      <a href="route_planner_w_microhub.php" class="menu-item">
        <i class="bx bx-trip"></i>
        <span class="links_name">Route Planner</span>
      </a>
    </li>
    <li>
      <a href="microhubs.php" class="menu-item">
        <i class="bx bx-package"></i>
        <span class="links_name">View micro hubs</span>
      </a>
    </li>
    <li>
      <a href="contact.php" class="menu-item">
        <i class="bx bx-message-rounded-dots"></i>
        <span class="links_name">Contact</span>
      </a>
    </li>
    <li>
      <a href="logout.php">
        <i class="bx bx-log-out"></i>
        <span class="links_name">Logout</span>
      </a>
    </li>
  </ul>
</div>
